include: package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  errors:
    sort_pub_dependencies: ignore
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
